development:
  secret_key_base: 'joruri_gw_secret_key_base_development_docker'
test:
  secret_key_base: 'joruri_gw_secret_key_base_test_docker'
production:
  secret_key_base: 'joruri_gw_secret_key_base_production_docker'
